config-version: 2 # Do not change this
bstats: true # Opt-out or opt-in to bStats
close-ports-on-stop: true # Close the ports when the server stops
ports:
  tcp: "25565" # Comma separated list of tcp ports to open
  udp: "25565" # Comma separated list of udp ports to open